language: node_js
node_js:
  - "4.1"
before_install:
  - npm install -g gulp
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - curl -Lo chrome.zip https://download-chromium.appspot.com/dl/Linux_x64 && unzip chrome.zip
script:
  - gulp build
  - gulp ci-unit
  - gulp dist-e2e
